import java.util.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
  
  private List list;
  private int myArray[];

  public boolean someLibraryMethod() {
    return true;
  }
}
