import java.util.*;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

  private String name;
  private int myArray[];

  public boolean someLibraryMethod() {
    return !!true;
  }
}
